### ISSUE TITLE
Project and data are deleted after reboot, constantly

### ISSUE THREAD

**Issue by MichalisVach** [frangoteam/FUXA#1138]
after HA reboot or plugin restart, the project is lost, 

**To Reproduce**
1. Go to 'restart either plugin either HA'
2. Click on 'web UI'
4. See error - No project there, everything is lost

**Comment by unocelli** [comment]
try to be more clear!

**Comment by MichalisVach** [comment]
> try to be more clear!

im sorry, 

im attaching you some pictures, 
Pic No:01
![image](https://github.com/frangoteam/FUXA/assets/72711850/76ced634-56a8-48ba-a5fa-5a50236c45d4)

this picture is as final project, 

when i restart HA or restart FUXA then everything are deleted, like the project is as temporary and after restart everything are lost,

![image](https://github.com/frangoteam/FUXA/assets/72711850/25f3098f-ce45-4b4a-9458-6471b7f516b8)

this is after restart, 
as you can see its at default settings, empty template, empty project,

**Comment by unocelli** [comment]
I suppose you are using docker, then you have to define the volume for _appdata:
docker run -d -p 1881:1881 -v fuxa_appdata:/usr/src/app/FUXA/server/_appdata -v fuxa_db:/usr/src/app/FUXA/server/_db -v fuxa_logs:/usr/src/app/FUXA/server/_logs -v fuxa_images:/usr/src/app/FUXA/server/_images frangoteam/fuxa:latest

**Comment by MattW2** [comment]
Hi, @MichalisVach. Let me give you a few tips when posting a bug and try to point you in the right direction. Not trying to be critical just give you some pointers to getting the best answer. 
1) Don't use acronyms for a software B when pointing in a repository for software A. I happen to know HA is most likely Home Assistance but most won't.
2) Use links to help people better understand what you are trying to to do. I assume you are using the addon from https://github.com/SmartLiving-Rocks/FUXA/ . 
3) If 2 is correct, posting in the bugs of that addon would actually be a better place as what I believe is happening is actually a bug in how the [config.ymal](https://github.com/SmartLiving-Rocks/FUXA/blob/main/config.yaml) is written.
4) Home Assistant add-ons are just docket containers. Docker containers by themselves have no "memory" meaning every time they reset they start from scratch. This is solved by mapping files/folder.... From outside the container into the container. Docker calls this a "bind mount". Looking at the config.ymal in the above linked Add-on from SmartLiving-Rocks I see no "map:" section. Which is why anything you do gets cleared out after a reset. I suggest you reach out to SmartLiving-Rocks and tell them this such that they can correct it.

**Comment by MichalisVach** [comment]
> I suppose you are using docker, then you have to define the volume for _appdata: docker run -d -p 1881:1881 -v fuxa_appdata:/usr/src/app/FUXA/server/_appdata -v fuxa_db:/usr/src/app/FUXA/server/_db -v fuxa_logs:/usr/src/app/FUXA/server/_logs -v fuxa_images:/usr/src/app/FUXA/server/_images frangoteam/fuxa:latest

Hi there, 

thank you for your reply, 

My Home Assitant is running in a Virtual Machine ( VirtualBox ) over Windows 11

**Comment by SmartLiving-Rocks** [comment]
Hello

I did the implementation of this absolutely amazing visualization tool for Home Assistant. This issue is not a fuxa related and I need to do some work on my site. 

> My Home Assitant is running in a Virtual Machine ( VirtualBox ) over Windows 11
You are runnig a Home Assistant Supervised. Supervised Home Assistant instances have an Add-On Store. Those Add-Ons are just Docker that looking a bit different. 

I have included the `map:` section to my `https://github.com/SmartLiving-Rocks/FUXA/blob/main/config.yaml`section as @MattW2 suggest. Thanks for the hint! 

But that did not do the trick and after a restart of the add-on all files are gone. 

> define the volume for _appdata:
I think I need to do also some modifications to the https://github.com/SmartLiving-Rocks/FUXA/blob/main/Dockerfile and do the right mapping of the `WORKDIR` and defining the volume for _appdata:

My Docker skills still have some room for improvements. I am working on a fix but it may take a while. 

## Workaround
Of curse I have also lost some of my fuxa Work. So here is how I save my projects at the moment. 
1. I save the project with the `Save project as` option locally to my pc.
2. After a restart of the add-on or the VM I use the `Open Project` file. 
3. The go to settings and `Connections` and insert your Username and Password in the MQTT section. 
4. Everything should be back and work normally.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
