### ISSUE TITLE
[FEATURE]Allow conveyors to stretch

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#1437]
@MatthewReed303

**Comment by MatthewReed303** [comment]
@hxjackcn this won't be easy using SVG since the preserveAspectRatio is at the SVG level and not the element level. What you could do is use inkscape to take the ends and middle section and split them into sperate SVGs, have the ends to keep aspect ratio and allow the middle section to stretch, and when done just group them in Fuxa.
