### ISSUE TITLE
[BUG] TDengine historian results in unordered points, also data structure in TDengine is poor

### ISSUE THREAD

**Issue by alext-extracellular** [frangoteam/FUXA#1489]
**Describe the bug**
When TDengine is configured as your DAQ server, reloading the Fuxa page to make graphs show historical data, results in the graphs showing seemingly unordered data from many different tags.
![Screenshot_20241108_165754](https://github.com/user-attachments/assets/c5b728d4-6cf7-4a8c-af5d-f3f23ee47b58)
In this image you can see these messy lines. The Agitation graph should show at 50 constantly, and the pH graph should show at 7.1 roughly. However in this image they have picked up some of each others values and therefore the graph is incorrect. 

Also, the data structure in TDengine created by FUXA is not very useful:
![image](https://github.com/user-attachments/assets/d7898a30-b7e0-4fea-b7b5-2d2d6193b68e)
It puts everything in one supertable, and also the type is not specific. 
The tag name is not kept in the database, so this makes it hard to query the database yourself without using Fuxa:
![image](https://github.com/user-attachments/assets/054589f4-31b9-461f-98f7-3bb3b8b85e00)

**To Reproduce**
1. Add Tdengine as DAQ
2. configure Fuxa to save certain tags from your device ( I am using OPCUA)
3. configure line charts to display these tags
4. let the data record for a while
5. Reload the page
6. view the graph with the wrong data being displayed

**Expected behavior**
Historical data is correctly recalled into the graph without confusion.

**Screenshots**

**Environment**
 - FUXA version: Version 1.1.19-1524 installed from dockerhub
 - Node.js version: n/a
 - npm version: n/a
 - Platform/OS: linux/docker
 - Browser: thorium

**Comment by henjoe** [comment]
Try the updated version 1.2.1 (this could be resolve related to tagid issue- I think someone has already PR this). 

For the data structure, I agree with you, they should have use the STable (like a template table) for each tags rather than joining all tag values in single STable. 
In total fairness to the developer team, they have done a good progress integrating TDEngine, it just that when it comes to optimizing data structure in storing data on a different databases engine requires some sort of expertise for that specific database.

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
