### ISSUE TITLE
This project cannot use reverse proxy.

### ISSUE THREAD

**Issue by Drincann** [frangoteam/FUXA#176]
For example:

I start the FUXA service at localhost:1881.

```js
const app = require('express')();
const proxy = require('express-http-proxy')

app.use('/proxy', proxy('http://localhost:1881'));

app.listen(80);
```
I visit

http://localhost/proxy

http://localhost/proxy/

http://localhost/proxy/home

http://localhost/proxy/home/

http://localhost/proxy/home/index.html

![image](https://user-images.githubusercontent.com/53897259/125758931-af084ee3-ceac-48a1-af9d-a20a8e5e4c78.png)

![image](https://user-images.githubusercontent.com/53897259/125759119-d1bba370-d917-4162-8d68-abc0b9c19ab1.png)

Static resource files seem to be accidentally loaded from absolute paths.

**Comment by unocelli** [comment]
Hi, sorry for the delay.
I don't know if I can help you, I've never tried with a proxy...we have to investigate.

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.

**Comment by children1987** [comment]
It seems that this issue has not been resolved yet. In the end, I used the backend cors middleware to solve the cross domain problem.
I'm a bit curious, since you've never used a proxy before, why isn't there any use of cors middleware in your backend code? I didn't even see the cors package installed. (There is no cors in server/package.json). Can I add the code for cors middleware with PR? I don't know if this will introduce other issues.
@unocelli

**Comment by children1987** [comment]
btw, I'm new in nodejs and angular.  Thank you so much for your perfect codes! @unocelli
