### ISSUE TITLE
Release Multi-Arch Docker Images with buildx

### ISSUE THREAD

**Issue by MRIIOT** [frangoteam/FUXA#204]
```
# install buildx 
sudo apt install gnupg2 pass
docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes
docker buildx create --name multiarch --driver docker-container --use
docker buildx inspect --bootstrap
sync
```

```
docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 --tag=frangoteam/fuxa:latest --push .
```

**Comment by unocelli** [comment]
Hi @MRIIOT, sorry for the delay. I have tried many times without ever succeeding.
I'm in ubuntu 20 and after having installed buildx I receive this error by `docker buildx build ...`
![Screenshot from 2021-11-15 21-15-14](https://user-images.githubusercontent.com/48684550/141850587-92e46cd2-7784-4817-a360-4d69790b768f.png)

do you have any idea why? thanks

**Comment by MRIIOT** [comment]
Hmm good question.  I think we're working with three different base images: https://hub.docker.com/r/arm64v8/node/, https://hub.docker.com/r/arm32v7/node/, and https://hub.docker.com/_/node.  

I wonder if the base image has to become a variable: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact, https://github.com/docker/buildx/issues/574

@bburns thoughts?

**Comment by bburns** [comment]
I don't know about manual builds - I ran into various problems also. I wound up using a GitHub workflow to do the cross-compilation builds in part because it took so long to do the QEMU versions (2-3hrs). The config is here - https://github.com/Ladder99/ladder99-ce/blob/main/.github/workflows/build-adapter.yml

Just click a button and it builds it for you, and pushes it to your Docker hub when done. You get a certain number of hours a month free.

**Comment by unocelli** [comment]
OK, interesting, let me try. 
Thanks
