### ISSUE TITLE
 fuxa-editor.js source code?

### ISSUE THREAD

**Issue by xujingzhou** [frangoteam/FUXA#44]
I want to see fuxa-editor.js source code, not fuxa-editor.min.js in client. Please tell me where I can find it.  Thanks!

**Comment by unocelli** [comment]
Hi,
I have not yet published the code of 'fuxa-editor.min.js' on github because
I would like to make a refactoring of this, and prefer to do it as soon as
it is finished (in any case the code is based on svg-edit version 2.8.1)

best regards

Il giorno mar 26 nov 2019 alle ore 08:13 Johnny Xu <notifications@github.com>
ha scritto:

**Comment by xujingzhou** [comment]
hi，
I want to extend several new graphic primitives on the edit panel, so I need the fuxa-editor.js source. Can you send the source code of fuxa-editor.js to my email (xujingzhou2016@gmail.com)?  Thank you very much!

**Comment by xujingzhou** [comment]
sorry，should be fuxa-editor.ts。thx
