### ISSUE TITLE
BUG   -  InfluxDB   Creating duplicate records !

### ISSUE THREAD

**Issue by tayfunonbasioglu** [frangoteam/FUXA#506]
When a new record information comes, it saves again with the previous record. Therefore, 4 records are created for 2 Tags in the same time period.

![image](https://user-images.githubusercontent.com/7642923/192061542-dcd14ae9-e439-4191-bbd8-cd7d35280993.png)

**Comment by unocelli** [comment]
Hi, thanks for the report.
it would be useful to know if the same problem occurs with the same configuration but on sqlite.

**Comment by tayfunonbasioglu** [comment]
Hi ,   sqlite no problem.

![image](https://user-images.githubusercontent.com/7642923/192100415-d20dc8c0-f836-4ef2-b8a9-58cfcdcdb56c.png)

**Comment by unocelli** [comment]
Hi, I suppose you have a polling interval smaller than 1 second and the reason is that timestamp in influxdb is truncate in seconds (you see the number of digits in sqlite are 13).
I checked and I see that the value are write in db after a conversion from milliseconds to Date...

function writePoint(tag, deviceName) {
  const point = new Point(tag.id)
  .tag('name', tag.name)
  .tag('type', tag.type)
  .timestamp(new Date(tag.timestamp));
  writeApi.writePoint(point);
}

**Comment by haitan981** [comment]
How do you query the data? I open the .db file and it's empty
![image](https://user-images.githubusercontent.com/44091731/203902354-7bc3c249-5dd1-4e39-bc35-1891bb3a1045.png)

**Comment by unocelli** [comment]
@haitan981 you have to enable the storage of tags data
