### ISSUE TITLE
buttons no response in mobile browsers when "zoom" enable

### ISSUE THREAD

**Issue by gahang** [frangoteam/FUXA#552]
Hi, when I enable "zoom", the buttons don't have any response when I touch them. it is normal in windows os, but abnormal in android/ios browsers such as chrome, safari and firefox

**Comment by unocelli** [comment]
Hi, which button are you speaking about, I have just tested in android with chrome and they work, the only one that does not work is 
![image](https://user-images.githubusercontent.com/48684550/197252515-d0301a4f-d935-4b3f-90f9-94a5ff4656a0.png)

**Comment by mauroalexandre** [comment]
what is your version? touch events in button are suported in the last version

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by GitTurboy** [comment]
This problem is still exist in v1.1.13-1204. You can repro it by steps below:
1. set zoom to "Manually" in the Layout Settings dialog
2. Create a button on one view which Event click is "Open Dialog" to any other view
3. Browse the view has button by "http://<you address>:1881/view?name=<the view name>" in edge/chrome or your andriod phone. 
4. if you use Edge or Chrome, Press Ctrl+Shift+I open developer tools and then Ctrl+Shift+M turn Device Simulator on.
5. Click the button
6. try to close the dialog opened on step 5. you will find the view loss reponse now7

**Comment by GitTurboy** [comment]
@unocelli  please take a look at this problem,thanks

**Comment by unocelli** [comment]
Hi, sorry for the delay, I can reproduce it. We will try to fix it. 
Workaround you can add a close button in the dialog.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
